[package]
name = "procbox"
version = "0.1.0"
edition = "2024"

[dependencies]
[dependencies]
clap = { version = "4.4", features = ["derive"] }
sysinfo = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nix = "0.27"
anyhow = "1.0"
